name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/test
        RAILS_ENV: test
        PG_USER: postgres
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - name: Run tests
        run: |
          bin/rails db:create db:migrate
          bundle exec rspec